project:
   type: website
   output-dir: docs

website:
   title: "Bright Shiny Code"
   navbar:
      left:
         - about.qmd
      right:
         - icon: github
           href: https://github.com/
         - icon: twitter
           href: https://twitter.com
   page-footer:
      left: "Copyright 2021, Norah Jones"
      right:
         - icon: github
           href: https://github.com/
         - icon: twitter
           href: https://twitter.com/

format:
   html:
      theme:
         light: flatly
         dark: darkly
      css: styles.css
